import { useCallback, useEffect, useMemo, useState } from 'react'
import './ForumPage.css'
import { api } from '../api/client'
import { useAuth } from '../auth/authContext'

const CATEGORIES = ['All', 'Historical Context', 'Geography', 'Translation', 'Archaeology', 'Theology']
const categoryOf = (title) => /^\[([^\]]+)\]\s*/.exec(title)?.[1] || 'General'
const cleanTitle = (title) => title.replace(/^\[[^\]]+\]\s*/, '')
const initials = (name = '?') => name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase()

function NewPost({ onClose, onCreated }) {
  const [category, setCategory] = useState('Historical Context'); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setError(''); try { onCreated(await api.post('/community/posts', { title: `[${category}] ${title.trim()}`, content: content.trim() })) } catch (caught) { setError(caught.message) } }
  return <div className="modal-overlay" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="new-post-modal"><div className="comments-header"><h2>Start a new discussion</h2><button className="modal-close" onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-field"><label>Category</label><select value={category} onChange={(event) => setCategory(event.target.value)}>{CATEGORIES.slice(1).map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-field"><label>Title</label><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength="180" required /></div><div className="form-field"><label>Your question or insight</label><textarea value={content} onChange={(event) => setContent(event.target.value)} maxLength="20000" rows="7" required /></div>{error && <p className="auth-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="cancel-btn" onClick={onClose}>Cancel</button><button className="auth-submit">Publish discussion</button></div></form></div></div>
}

function Discussion({ post, user, onClose, onChanged }) {
  const [comments, setComments] = useState([]); const [content, setContent] = useState(''); const [error, setError] = useState('')
  useEffect(() => { api.get(`/community/posts/${post.id}/comments`).then(setComments).catch((caught) => setError(caught.message)) }, [post.id])
  const reply = async (event) => { event.preventDefault(); try { const item = await api.post(`/community/posts/${post.id}/comments`, { content }); setComments((items) => [...items, item]); setContent('') } catch (caught) { setError(caught.message) } }
  const removeComment = async (id) => { if (!window.confirm('Delete this reply?')) return; await api.delete(`/community/comments/${id}`); setComments((items) => items.filter((item) => item.id !== id)) }
  return <div className="modal-overlay" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="comments-modal"><div className="comments-header"><h2>{cleanTitle(post.title)}</h2><button className="modal-close" onClick={onClose}>×</button></div><div className="original-post-content"><div className="post-author-row"><span className="author-avatar">{initials(post.author.username)}</span><span className="author-name">{post.author.username}</span></div><p>{post.content}</p></div><div className="comments-list"><h3>Discussion ({comments.length})</h3>{comments.map((comment) => <article key={comment.id} className="comment-item"><div className="comment-author-row"><span className="author-avatar small">{initials(comment.author.username)}</span><span className="author-name">{comment.author.username}</span>{user && (user.id === comment.author.id || ['moderator', 'admin'].includes(user.role)) && <button onClick={() => removeComment(comment.id)}>Delete</button>}</div><p className="comment-text">{comment.content}</p></article>)}{comments.length === 0 && <p className="no-comments">Be the first to reply.</p>}</div>{user ? <form className="comment-form" onSubmit={reply}><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Share your perspective. Use @username to mention someone." rows="3" required /><button>Post reply</button></form> : <div className="sign-in-prompt">Sign in with your Unbound Bible account to join the discussion.</div>}{error && <p role="alert" className="auth-error">{error}</p>}{user && (user.id === post.author.id || ['moderator', 'admin'].includes(user.role)) && <button className="cancel-btn" onClick={async () => { if (window.confirm('Delete this discussion?')) { await api.delete(`/community/posts/${post.id}`); onChanged(); onClose() } }}>Delete discussion</button>}</div></div>
}

export default function ForumPage() {
  const { user } = useAuth(); const [posts, setPosts] = useState([]); const [category, setCategory] = useState('All'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(null); const [creating, setCreating] = useState(false); const [state, setState] = useState('loading')
  const load = useCallback(() => { setState('loading'); api.get('/community/posts').then((data) => { setPosts(data); setState('ready') }).catch(() => setState('error')) }, [])
  useEffect(load, [load])
  const filtered = useMemo(() => posts.filter((post) => (category === 'All' || categoryOf(post.title) === category) && `${post.title} ${post.content}`.toLowerCase().includes(query.toLowerCase())), [posts, category, query])
  return <div className="forum-page"><section className="forum-hero"><div><span className="forum-eyebrow">THE UNBOUND COMMUNITY</span><h1>Study in conversation</h1><p>Ask careful questions, share sources, and learn alongside readers across traditions.</p></div>{user ? <button className="new-discussion-btn" onClick={() => setCreating(true)}>Start a discussion</button> : <p className="sign-in-prompt">Sign in above to participate.</p>}</section><div className="forum-controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search discussions" aria-label="Search discussions" /><div className="category-tabs">{CATEGORIES.map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></div>{state === 'loading' && <p role="status">Loading discussions…</p>}{state === 'error' && <div className="empty-workspace-card" role="alert">Community discussions are temporarily unavailable. <button onClick={load}>Try again</button></div>}<div className="posts-list">{state === 'ready' && filtered.length === 0 && <div className="empty-workspace-card">No discussions match yet. Start a thoughtful one.</div>}{filtered.map((post) => <article key={post.id} className="post-card" onClick={() => setSelected(post)}><div className="post-author-row"><span className="author-avatar">{initials(post.author.username)}</span><span className="author-name">{post.author.username}</span><span className="post-category">{categoryOf(post.title)}</span></div><h2>{cleanTitle(post.title)}</h2><p>{post.content}</p><div className="post-meta"><span>{post.comments_count} replies</span><button>Open discussion →</button></div></article>)}</div>{creating && <NewPost onClose={() => setCreating(false)} onCreated={(post) => { setPosts((items) => [post, ...items]); setCreating(false) }} />}{selected && <Discussion post={selected} user={user} onClose={() => setSelected(null)} onChanged={load} />}</div>
}
